Training.UI/Models/ErrorViewModel.cs
using System;

namespace Training.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Training.UI/Models/MonsterSlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Training.UI.Models
{
    public class MonsterSlayerViewModel 
    {
        public int MonsterHealth { get; set; } = 100;
        public int PlayerHealth { get; set; } = 100;
        public int PlayerMaxHitModifier { get; set; } = 5;
        public int PlayerMinHitModifier { get; set; } = 12;
        public int MonsterMaxHitModifier { get; set; } = 8;
        public int MonsterMinHitModifier { get; set; } = 15;
        public int SpecialAttackMaximum { get; set; } = 3;

        public List<object> BattleLog { get; set; } = new List<object>();
    }
}

Training.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Training.UI.Models;

namespace Training.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Module2()
        {
            return View("~/Views/Home/Module2.cshtml");
        }

        public IActionResult Module3()
        {
            return View("~/Views/Home/Module3/Module.cshtml");
        }

        public IActionResult Assignment1()
        {
            return View("~/Views/Home/Assignment1.cshtml");
        }

        public IActionResult Assignment2()
        {
            return View("~/Views/Home/Assignment2.cshtml");
        }
        public IActionResult Assignment3()
        {
            return View("~/Views/Home/Assignment3.cshtml");
        }
        
        public IActionResult Assignment4()
        {
            return View("~/Views/Home/Assignment4.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Training.UI/Controllers/Module3Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Training.UI.Models;

namespace Training.UI.Controllers
{
    public class Module3Controller: Controller
    {
        private readonly ILogger<Module3Controller> _logger;

        public Module3Controller(ILogger<Module3Controller> logger)
        {
            _logger = logger;
        }

        public IActionResult Assignment1()
        {
            return View("~/Views/Home/Module3/Assignment1.cshtml");
        }

        public IActionResult Assignment2()
        {
            return View("~/Views/Home/Module3/Assignment2.cshtml");
        }
        public IActionResult Assignment3()
        {
            return View("~/Views/Home/Module3/Assignment3.cshtml");
        }
        
        public IActionResult Assignment4()
        {
            return View("~/Views/Home/Module3/Assignment4.cshtml");
        }
    }
}

Training.UI/Controllers/Module4Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Training.UI.Controllers
{
    public class Module4Controller : Controller
    {
        public IActionResult Module()
        {
            return View("~/Views/Home/Module4/Module.cshtml");
        }
        public IActionResult Assignment1()
        {
            return View("~/Views/Home/Module4/Assignment1.cshtml");
        }
    }
}

Training.UI/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Training.UI.Models;

namespace Training.UI.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult MonsterSlayer()
        {
            return View("~/Views/Projects/MonsterSlayer.cshtml", new MonsterSlayerViewModel());
        }
    }
}

Training.UI/Views/Home/Assignment1.cshtml
@{
    ViewData["Title"] = "Assignment1";
}

<h1>Assignment1</h1>
<section id="user-description" class="card shadow-lg">
    <div class="card-header ">
        <h2 class="w-100 text-center p-3">{{ userName }}</h2>
    </div>
    <div class="card-body d-flex justify-content-center">
        <div class="w-50">
            <p v-bind:class="textClass">Age - {{ userAge }}</p>
            <p v-bind:class="textClass">Age in 5 years: {{ getUserFutureAge() }}</p>
            <p v-bind:class="textClass">Favorite Number: {{ randomNumber }}</p>
            <p v-bind:class="textClass" v-for="input in userDefinedInput">{{ input }}</p>
        </div>
    </div>
    <div class="card-footer container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center my-1">
                <img v-bind:src="getGoogleImage()" style="max-height: 200px; max-width:200px;" />
            </div>
            <div class="col-12 d-flex justify-content-center">
                <input type="text" v-model="inputValue" class="w-100 text-center bg-white form-control-plaintext border rounded" v-on:keyup="userEnteredValue"/>
            </div>
        </div>
    </div>
</section>


<script>
    const app = Vue.createApp({
        data() {
            return {
                inputDefault: 'Please input value',
                inputValue: 'Please input value',
                userName: 'Jesse Pecar',
                userAge: 25,
                textClass: 'w-100 text-center font-lg badge badge-success bg-purple rounded-pill py-1 mx-1',
                randomNumber: Math.floor(Math.random() * 100),
                userDefinedInput: []
            };
        },
        methods: {
            getGoogleImage() {
                if (this.randomNumber < 25) {
                    return 'https://static01.nyt.com/images/2020/12/23/business/23Techfix-illo/23Techfix-illo-mediumSquareAt3X.jpg';
                } else if (this.randomNumber < 50) {
                    return 'https://thoughtcatalog.com/wp-content/uploads/2018/08/vampire-movies.jpg?w=1920&h=1280&crop=1&resize=1920,1280&quality=95&strip=all';
                } else if (this.randomNumber < 75) {
                    return 'https://www.brookings.edu/wp-content/uploads/2017/11/metro_20171121_tech-empowers-tech-polarizes-mark-muro.jpg';
                } else {
                    return 'https://hmg-prod-io.hearstapps.com/images/tech-gifts-2020-1605302505.jpg?&auto=webp';
                }
            },
            getUserFutureAge() {
                return this.userAge + 5;
            },

            userEnteredValue: function(e) {
                if (e.keyCode === 13) {
                    this.randomNumber = Math.random();
                    this.userDefinedInput.push(this.inputValue);

                    this.inputValue = this.inputDefault;
                }
            }
        }

    });

    app.mount('#user-description');
</script>

Training.UI/Views/Home/Assignment2.cshtml
@{
    ViewData["Title"] = "Assignment2";
}

<h1>Assignment 2 - Events</h1>
<section id="user-description" class="card shadow-lg">
    <div class="card-header ">
        <h2 class="w-100 text-center p-3">Event Practice</h2>
    </div>
    <div class="card-body d-flex flex-column">
        <div class="w-100 d-flex justify-content-center">
            <button class="btn btn-danger w-25" v-on:click.prevent="showAlert()">Show Alert</button>
        </div>
        <hr />
        <div class="d-flex justify-content-center w-100">
            <div class="d-flex flex-column w-50">
                <div class="w-100 d-flex justify-content-center">
                    <!-- Key Down output (event.target.value)-->
                    <input type="text" class="w-50 my-1" v-on:keyup="onKeyDown" />
                </div>
                <div class="w-100 d-flex justify-content-center">
                    <p class="font-lg badge badge-success w-50 my-1">Output: {{ keyDownText }}</p>
                </div>
            </div>
        </div>
        <hr />
        <div class="d-flex justify-content-center w-100">
            <div class="d-flex flex-column w-50">
                <div class="w-100 d-flex justify-content-center">
                    <!-- Show the output text when the enter key is pressed -->
                    <input type="text" class="w-50 my-1" v-on:keydown.enter="submitTextKeyUp" v-model="enterText" />
                </div>
                <div class="w-100 d-flex justify-content-center">
                    <p class="font-lg badge badge-success w-50 my-1">Output: {{ submitText }}</p>
                </div>
            </div>
        </div>
    </div>

</section>


<script>
    const app = Vue.createApp({
        data() {
            return {
                keyDownText: '',
                enterText: '',
                submitText: ''
            };
        },
        methods: {
            showAlert() {
                alert("Submit button pressed!");
            },
            onKeyDown(event) {
                this.keyDownText = event.target.value;
            },
            submitTextKeyUp(event) {
                this.submitText = this.enterText;

            }
        }

    });

    app.mount('#user-description');
</script>

Training.UI/Views/Home/Assignment3.cshtml
@{
    ViewData["Title"] = "Assignment2";
}

<h1>Assignment 3 - Reactivity</h1>
<section id="user-description" class="card shadow-lg">
    <div class="card-header ">
        <h2 class="w-100 text-center p-3">Reactivity in Action</h2>
    </div>
    <div class="card-body row">
        <div class="col-2"></div>
        <div class="d-flex justify-content-around col-8">
            <button class="btn btn-danger" v-on:click="increment(5)">Add 5</button>
            <button class="btn btn-danger" v-on:click="increment(1)">Add 1</button>
        </div>
        <div class="col-2"></div>
        <div class="col-2"></div>
        <div class="d-flex justify-content-around col-8">
            <p class="badge badge-success font-lg">Result: {{ result }}</p>
        </div>
        <div class="col-2"></div>
    </div>

</section>


<script>
    const app = Vue.createApp({
        data() {
            return {
                count: 0
            };
        },
        computed: {
            result() {
                if (this.count < 37) {
                    return 'Not There Yet!';
                } else if (this.count > 37) {
                    return 'Too Much!';
                } else {
                    return 'Hooray!';
                }
            }
        },
        watch: {
            result() {
                setTimeout(this.resetCount, 5000)
            }
        },
        methods: {
            increment(value) {
                this.count += value;
            },
            resetCount() {
                this.count = 0;
            }
        }

    });

    app.mount('#user-description');

</script>

Training.UI/Views/Home/Assignment4.cshtml
@{
    ViewData["Title"] = "Assignment2";
}

<h1>Assignment 4 - Vue Styling</h1>
<section id="vue-styling" class="card shadow-lg">
    <div class="card-header ">
        <h2 class="w-100 text-center p-3">Dynamic Styling</h2>
    </div>
    <div class="card-body">
        <div class="container">
            <input class="form-text my-1" v-model="enteredBadge"/>
            <p :class="['badge', 'my-1', {'d-block': isVisible}, enteredBadge, {'d-none': !isVisible}]">Style Me!</p>
            <button class="btn btn-success my-1" v-on:click="onButtonClick">Toggle Paragraph</button>
            <input class="form-text my-1" v-model="enteredColor"/>
            <p class="my-1" :style="{'background-color': enteredColor}">Style Me Inline!</p>
        </div>
    </div>

</section>


<script>
    const app = Vue.createApp({
        data() {
            return {
                enteredBadge: 'badge-',
                isVisible: true,
                enteredColor: '#DDDDDD'
            };
        },
        computed: {
           
        },
        watch: {

        },
        methods: {
            onButtonClick() {
                this.isVisible = !this.isVisible;
            }
        }
    });

    app.mount('#vue-styling');

</script>

Training.UI/Views/Home/Index.cshtml
<div id="graphics" class="p-3 mt-3 shadow-lg">
    <div class="form-group p-1">
        <label for="goal" class="mb-1">Goal</label>
        <input type="text" class="form-control mb-1" v-model="enteredValue" id="goal" />
        <button class="btn btn-primary" v-on:click="addGoal">Add Goal</button>
    </div>
    <hr />
    <ul class="list-group list-group-flush" id="">
        <li class="list-group-item" v-for="goal in goals">{{ goal }}</li>
    </ul>
    <div id="app">
    </div>
</div>
<script>
    Vue.createApp({
        data: function() {
        return {
            goals: [],
            enteredValue: ''
        };
    },
        methods: {
            addGoal() {
                this.goals.push(this.enteredValue);
                this.enteredValue = '';
            }
    }
    }).mount('#graphics');


</script>

Training.UI/Views/Home/Module3/Assignment1.cshtml
@{
    ViewData["Title"] = "Assignment 1";
}

<h1>Assignment 1</h1>
<section id="conditional-content" class="card shadow-lg">
    <div class="card-header ">
        <h2 class="w-100 text-center p-3">Assignment</h2>
    </div>
    <div class="card-body d-flex justify-content-center">
        <div class="container">

        <div class="input-group">
            <input class="form-text" v-model="task" v-on:keyup.enter="addTask" />
            <button class="btn btn-light btn-outline-danger input-group-append" v-on:click="addTask">Add Task</button>
        </div>
        <ul class="list-group list-inline mt-3" v-if="showTasks">
            <li class="list-group-item" v-for="t in taskGroup">{{ t }}</li>
        </ul>
        </div>
    </div>
    <div class="card-footer container">
        <button class="btn btn-danger" v-on:click="toggleList">{{ showList ? 'Hide' : 'Show'}} List</button>
    </div>
</section>


<script>
    const app = Vue.createApp({
        data() {
            return {
                task: '',
                taskGroup: [],
                showList: false
            };
        },
        methods: {
            addTask() {
                this.taskGroup.push(this.task);
                this.task = '';
            },
            toggleList() {
                this.showList = !this.showList;
            }
        },
        computed: {
            showTasks() {
                return this.taskGroup.length > 0 && this.showList;
            }
        }
    });

    app.mount('#conditional-content');
</script>

Training.UI/Views/Home/Module3/Module.cshtml
@{
    ViewData["Title"] = "Module 3";
}

<div class="shadow-lg bg-dark p-3 mb-1 rounded">
    <div class="btn-group">
        <a class="btn btn-light rounded-pill mx-1" asp-controller="Module3" asp-action="Assignment1" type="submit">Assignment 1</a>
    </div>
</div>

<div id="moduleApp" class="rounded">
    <div class="card shadow mb-3">
        <div class="card-header bg-success d-flex justify-content-center">
            <h1 class="text-white text-center">Vue.js Course Goals</h1>
        </div>
    </div>
</div>
<div class="container">
    <div id="my-course-goals" class="card">
        <div class="card-header">
            <h2 class="font-lg text-success">My Course Goals</h2>
        </div>
        <div class="card-body">
            <div class="input-group">
                <input type="text" v-model="enteredGoalValue" class="form-text" v-on:keyup.enter="addGoal" />
                <button class="btn btn-danger input-group-append" v-on:click="addGoal">Add Goal</button>
            </div>
        </div>
        <div v-if="goalEmpty" class="px-5">
            <p class="alert alert-warning">
                No goals have been added yet - please start adding some!
            </p>
        </div>
        <div v-else class="px-5 my-1">
            <ul class="list-group list-inline">
                <li v-for="(goal, index) in goals" :key="goal" class="list-group-item-success my-1" v-on:click="removeGoal(index)">
                    <div class="container py-2">
                        <p class="font-lg">{{ goal }}</p>
                        <input type="text" v-on:click.stop />
                    </div>
                </li>
            </ul>
            <!--<ul class="list-group list-inline">
                <li v-for="(value, key) in {name: 'Jesse', age: 25}" class="list-group-item-success my-1">{{ key }}: {{ value }}</li>
            </ul>
            <ul class="list-group list-inline">
                <li v-for="num in 10" class="list-group-item-success my-1">{{ num }}</li>
            </ul>-->
        </div>
    </div>

</div>

<script>
    const part1 = Vue.createApp({
        data() {
            return {
                enteredGoalValue: '',
                goals: []
            }
        },
        methods: {
            addGoal() {
                if (this.enteredGoalValue !== '') {
                    this.goals.push(this.enteredGoalValue);
                    this.enteredGoalValue = '';
                }
            },
            removeGoal(idx) {
                this.goals.splice(idx, 1);
            }
        },
        computed: {
            goalEmpty() {
                return this.goals.length === 0;
            }
        }
    });

    part1.mount('#my-course-goals')
</script>

Training.UI/Views/Home/Module4/Assignment1.cshtml
@{
    ViewData["Title"] = "Assignment 1";
}
<div class="bg-purple m-0 w-100 p-2 d-flex justify-content-center">
    <h1 class="text-white">Remember Me</h1>
</div>



<script>

</script>

Training.UI/Views/Home/Module4/Module.cshtml
@{
    ViewData["Title"] = "Module 4";
}

<div class="shadow-lg bg-dark p-3 mb-1 rounded">
    <div class="btn-group">
        <a class="btn btn-light rounded-pill mx-1" asp-controller="Module4" asp-action="Assignment1" type="submit">Assignment 1</a>
    </div>
</div>

<div id="moduleApp" class="rounded">
    <div class="card shadow mb-3">
        <div class="card-header bg-success d-flex justify-content-center">
            <h1 class="text-white text-center">Friends List</h1>
        </div>
    </div>
</div>
<div class="container" id="module-5-app">
    <ul class="list-group-flush">
        <friend-list></friend-list>
        <friend-list></friend-list>
    </ul>


</div>

<script>
    const part1 = Vue.createApp({});

    part1.component('friend-list', {
        template: `
        <li class="list-group-item" :key="friend.id">
            <div class="card">
                <div class="card-header w-100 d-flex justify-content-center"><h2>{{ friend.name }}</h2></div>
                <div class="card-body">
                    <div class="w-100 d-flex justify-content-center my-1">
                        <button class="btn btn-danger" v-on:click="toggleDetails">Show Details</button>
                    </div>
                    <ul class="list-group-flush list-group" v-if="detailsAreVisible">
                        <li class="list-group-item">
                            <div class="rounded shadow p-2 my-1">
                                <p><strong>Phone:</strong> {{ friend.phone }}</p>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="rounded shadow p-2 my-1">
                                <p><strong>Email:</strong> {{friend.email}}</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
        `,
        data() {
            return {
                detailsAreVisible: false,
                friend: {
                    id: 'friend-1',
                    name: 'My Only Friend',
                    phone: '(123)456-7890',
                    email: 'some@email.com'
                }
            };
        },
        methods: {
            toggleDetails() {
                this.detailsAreVisible = !this.detailsAreVisible;
            }
        }
    });

    part1.mount('#module-5-app ');
</script>

Training.UI/Views/Projects/MonsterSlayer.cshtml
@model Training.UI.Models.MonsterSlayerViewModel
@using Newtonsoft.Json;
@using Newtonsoft.Json.Serialization;
@using System.Web;
@{
    ViewData["Title"] = "Monster Slayer";

    var serializationSettings = new JsonSerializerSettings()
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver(),
        StringEscapeHandling = StringEscapeHandling.EscapeHtml
    };

    var data = Html.Raw(
             HttpUtility.JavaScriptStringEncode(
                JsonConvert.SerializeObject(
                    Model, Formatting.None, serializationSettings
                ),
             false)
        );
}
<div id="monster-slayer-container" class="container">
    <div class="card bg-danger m-0 show my-2">
        <h1 class="text-white font-weight-bolder w-100 text-center py-5">Monster Slayer</h1>
    </div>
    <div class="card my-2">
        <div class="card-header">
            <h3 class="w-100 text-center">Monster Health</h3>
        </div>
        <div class="card-body">
            <div class="bg-danger" style="height: 30px;" :style="{width: monsterHealthPercent}">
                <h3 class="w-100 text-center">{{ monsterHealth }}</h3>
            </div>
        </div>
    </div>
    <div class="card my-2">
        <div class="card-header">
            <h3 class="w-100 text-center">Your Health</h3>
        </div>
        <div class="card-body">
            <div class="bg-success" style="height: 30px;" :style="{width: playerHealthPercent}">
                <h3 class="w-100 text-dark text-center">{{ playerHealth }}</h3>
            </div>
        </div>
    </div>
    <div v-if="didPlayerWin" class="card my-2">
        <div class="card-body">
            <p class="text-center">You Win! You have defeated the big bad monster.</p>
        </div>
        <div class="card-footer">
            <div class="w-100 d-block">
                <a class="text-primary float-right" asp-controller="Project" asp-action="MonsterSlayer">Play Again?</a>
            </div>
        </div>
    </div>
    <div v-else-if="didMonsterWin" class="card my-2">
        <div class="card-body">
            <p class="text-center">You Lose! You unfortunately lost to the big bad monster.</p>
        </div>
        <div class="card-footer">
            <div class="w-100 d-block">
                <a class="text-primary float-right" asp-controller="Project" asp-action="MonsterSlayer">Play Again?</a>
            </div>
        </div>
    </div>
    <div v-else class="row my-2">
        <div class="col-1"></div>
        <div class="col-5 my-1 px-2"><button class="w-100 py-2 btn btn-primary" v-on:click="attackMonster">ATTACK</button></div>
        <div class="col-5 my-1 px-2"><button class="w-100 py-2 btn btn-primary" v-on:click="specialAttack" :disabled="disableSpecialAttck">SPECIAL ATTACK</button></div>
        <div class="col-1"></div>


        <div class="col-1"></div>
        <div class="col-5 my-1 px-2"><button class="w-100 py-2 btn btn-primary" v-on:click="playerHeal">HEAL</button></div>
        <div class="col-5 my-1 px-2"><button class="w-100 py-2 btn btn-primary" v-on:click="playerSurrender">SURRENDER</button></div>
        <div class="col-1"></div>
    </div>


    <div class="card my-2">
        <div class="card-header">
            <div class="w-100 d-flex justify-content-center">
                <h3 class="bg-warning rounded text-dark font-lg py-2 px-4">Battle Log</h3>
            </div>
        </div>
        <div class="card-body">
            <ul class="list-inline">
                <li class="" v-for="log in battleLog">
                    <div>
                        <!-- this.battleLog.push({ source: 'Player', damage: attackValue, isSpecialAttack: false, isHeal: false})-->
                        <span :class="[getClassFromSource(log.source)]">{{ log.source }} </span>
                        <span> {{ getLogDescription(log) }} for </span>
                        <span :class="[getTextDecorationForHealthMod(log.isHeal)]">{{ log.damage }} health</span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
    function getRandomValue(min, max) {
        return Math.floor(Math.random() * (max - min)) + min
    }

    const monsterSlayerApp = Vue.createApp({
        data() {
            return JSON.parse('@data')
            
        },
        watch: {
            monsterHealth() {
                if (this.monsterHealth < 0) {
                    this.monsterHealth = 0;
                }
            },
            playerHealth() {
                if (this.playerHealth < 0) {
                    this.playerHealth = 0;
                }
            }
        },
        computed: {
            playerHealthPercent() {
                return this.playerHealth + '%';
            },
            monsterHealthPercent() {
                return this.monsterHealth + '%';
            },
            disableSpecialAttck() {
                if (this.specialAttackMaximum <= 0) {
                    return true;
                }
                return false;
            },
            didPlayerWin() {
                return this.monsterHealth <= 0;
            },
            didMonsterWin() {
                return this.playerHealth <= 0;
            }
        },
        methods: {
            attackMonster() {
                const attackValue = getRandomValue(this.playerMinHitModifier, this.playerMaxHitModifier);
                this.monsterHealth -= attackValue;
                this.battleLog.push({ source: 'Player', damage: attackValue, isSpecialAttack: false, isHeal: false})
                if (this.monsterHealth > 0) {
                    this.attackPlayer();
                }
            },
            attackPlayer() {
                const attackValue = getRandomValue(this.monsterMinHitModifier, this.monsterMaxHitModifier);
                this.playerHealth -= attackValue;
                this.battleLog.push({ source: 'Monster', damage: attackValue, isSpecialAttack: false, isHeal: false })
            },
            specialAttack() {
                const attackValue = getRandomValue(this.playerMinHitModifier + 5, this.playerMaxHitModifier + 7);
                this.monsterHealth -= attackValue;
                this.specialAttackMaximum -= 1;
                this.battleLog.push({ source: 'Player', damage: attackValue, isSpecialAttack: true, isHeal: false })
                this.attackPlayer();
            },
            playerHeal() {
                const healValue = getRandomValue(this.monsterMinHitModifier * 2, this.monsterMaxHitModifier * 2);
                this.playerHealth += healValue;
                this.battleLog.push({ source: 'Player', damage: healValue, isSpecialAttack: false, isHeal: true })
                this.attackPlayer();
            },
            playerSurrender() {
                this.playerHealth = 0;
            },
            getClassFromSource(source) {
                if (source === 'Player') return 'text-success'
                return 'text-danger'
            },
            getLogDescription(log) {
                if (log.isSpecialAttack) return ' special attacked';
                else if (log.isHeal) return ' healed';
                return ' attacked';
            },
            getTextDecorationForHealthMod(isHeal) {
                if (isHeal) return 'text-success';
                return 'text-danger';
            }
        }

    });

    monsterSlayerApp.mount('#monster-slayer-container');
</script>

Training.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Training.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap-custom-theme.css" />
    <script src="https://unpkg.com/vue@next"></script>
</head>
<body>
    <header class="bg-primary">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Training.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Module2">Module 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Module3">Module 3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Module4" asp-action="Module">Module 4</a>
                        </li>
                    </ul>
                    <div class="dropdown nav-item">
                        <a class="dropdown-toggle nav-link text-white" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Projects
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item text-primary" asp-controller="Project" asp-action="MonsterSlayer">Monster Slayer</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Training.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/app.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>